### ISSUE TITLE
Cannot read property 'socket' of undefined

### ISSUE THREAD

**Issue by GBoucher42** [stuartZhang/coexist-parser-proxy#2]
Whenever I make a call that is not proxied, I get the error below

(node:19) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'socket' of undefined
dev_1  |     at clearIncoming (_http_server.js:658:22)
dev_1  |     at /app/node_modules/coexist-parser-proxy/index.js:43:29
dev_1  |     at Generator.next (<anonymous>)
dev_1  |     at onFulfilled (/app/node_modules/co/index.js:65:19)
dev_1  |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
dev_1  | (node:19) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

**Comment by GBoucher42** [comment]
If i add present the call of "clearIncoming" on line 41 + of your index.js by adding the following condition, it seems to still work as intended without the error log. 

                 for (const endCallback of endCallbacks) {
                        for (const endEvent of cacheEvents.end) {
                            if(endCallback.name !== "clearIncoming")
                                endCallback(endEvent);
                            yield waitTick();
                        }
                    }
